import { InternalApi } from 'nitropack/types'

export const PermissionConstant: Partial<Record<keyof InternalApi, string>> = {
  '/api/system/config/create': 'sys.menu.system.config.create',
  '/api/system/config/findPage': 'sys.menu.system.config.findPage',
  '/api/system/config/remove': 'sys.menu.system.config.remove',
  '/api/system/config/update': 'sys.menu.system.config.update',
  '/api/system/dept/create': 'sys.menu.system.dept.create',
  '/api/system/dept/findList': 'sys.menu.system.dept.findList',
  '/api/system/dept/remove': 'sys.menu.system.dept.remove',
  '/api/system/dept/update': 'sys.menu.system.dept.update',
  '/api/system/dict/data/create': 'sys.menu.system.dictData.create',
  '/api/system/dict/data/findList': 'sys.menu.system.dictData.findList',
  '/api/system/dict/data/remove': 'sys.menu.system.dictData.remove',
  '/api/system/dict/data/update': 'sys.menu.system.dictData.update',
  '/api/system/dict/type/create': 'sys.menu.system.dictType.create',
  '/api/system/dict/type/findPage': 'sys.menu.system.dictType.findPage',
  '/api/system/dict/type/remove': 'sys.menu.system.dictType.remove',
  '/api/system/dict/type/update': 'sys.menu.system.dictType.update',
  '/api/system/menu/findList': 'sys.menu.system.menu.findList',
  '/api/system/menu/create': 'sys.menu.system.menu.create',
  '/api/system/menu/remove': 'sys.menu.system.menu.remove',
  '/api/system/menu/update': 'sys.menu.system.menu.update',
  '/api/system/post/create': 'sys.menu.system.post.create',
  '/api/system/post/findPage': 'sys.menu.system.post.findPage',
  '/api/system/post/remove': 'sys.menu.system.post.remove',
  '/api/system/post/update': 'sys.menu.system.post.update',
  '/api/system/role/create': 'sys.menu.system.role.create',
  '/api/system/role/findPage': 'sys.menu.system.role.findPage',
  '/api/system/role/remove': 'sys.menu.system.role.remove',
  '/api/system/role/update': 'sys.user.system.role.update',
  '/api/system/user/create': 'sys.menu.system.user.create',
  '/api/system/user/findPage': 'sys.menu.system.user.findPage',
  '/api/system/user/remove': 'sys.menu.system.user.remove',
  '/api/system/user/update': 'sys.menu.system.user.update',
  '/api/system/role/auth/allocateUser': 'sys.menu.system.roleAuth.allocateUser',
  '/api/system/role/auth/findAllocatedUserPage': 'sys.menu.system.roleAuth.findAllocatedUserPage',
  '/api/system/role/auth/findUnallocatedUserPage': 'sys.menu.system.roleAuth.findUnallocatedUserPage',
  '/api/system/role/auth/unallocateUser': 'sys.menu.system.roleAuth.unallocateUser',
  '/api/system/role/menu/assign': 'sys.menu.system.roleMenu.assign',
  '/api/system/role/menu/assigned': 'sys.menu.system.roleMenu.assigned',
}
