import { defineEnum, IEnumType } from './base.js'

export const httpStatusEnum = defineEnum({
  CONTINUE: { label: '继续', value: 100 },
  SWITCHING_PROTOCOLS: { label: '切换协议', value: 101 },
  PROCESSING: { label: '处理中', value: 102 },
  EARLYHINTS: { label: '提前提示', value: 103 },
  OK: { label: '成功', value: 200 },
  CREATED: { label: '创建成功', value: 201 },
  ACCEPTED: { label: '已接受', value: 202 },
  NON_AUTHORITATIVE_INFORMATION: { label: '非授权信息', value: 203 },
  NO_CONTENT: { label: '无内容', value: 204 },
  RESET_CONTENT: { label: '重置内容', value: 205 },
  PARTIAL_CONTENT: { label: '部分内容', value: 206 },
  AMBIGUOUS: { label: '模糊', value: 300 },
  MOVED_PERMANENTLY: { label: '永久移动', value: 301 },
  FOUND: { label: '找到', value: 302 },
  SEE_OTHER: { label: '查看其它', value: 303 },
  NOT_MODIFIED: { label: '未修改', value: 304 },
  TEMPORARY_REDIRECT: { label: '临时重定向', value: 307 },
  PERMANENT_REDIRECT: { label: '永久重定向', value: 308 },
  BAD_REQUEST: { label: '请求错误', value: 400 },
  UNAUTHORIZED: { label: '未授权', value: 401 },
  PAYMENT_REQUIRED: { label: '需要付费', value: 402 },
  FORBIDDEN: { label: '禁止', value: 403 },
  NOT_FOUND: { label: '找不到', value: 404 },
  METHOD_NOT_ALLOWED: { label: '方法不允许', value: 405 },
  NOT_ACCEPTABLE: { label: '不可接受', value: 406 },
  PROXY_AUTHENTICATION_REQUIRED: { label: '代理身份验证要求', value: 407 },
  REQUEST_TIMEOUT: { label: '请求超时', value: 408 },
  CONFLICT: { label: '冲突', value: 409 },
  GONE: { label: '已删除', value: 410 },
  LENGTH_REQUIRED: { label: '需要长度', value: 411 },
  PRECONDITION_FAILED: { label: '条件失败', value: 412 },
  PAYLOAD_TOO_LARGE: { label: '请求实体过大', value: 413 },
  URI_TOO_LONG: { label: '请求地址过长', value: 414 },
  UNSUPPORTED_MEDIA_TYPE: { label: '不支持的媒体类型', value: 415 },
  REQUESTED_RANGE_NOT_SATISFIABLE: { label: '请求范围不符合要求', value: 416 },
  EXPECTATION_FAILED: { label: '期望失败', value: 417 },
  I_AM_A_TEAPOT: { label: '我是茶壶', value: 418 },
  MISDIRECTED: { label: '重定向错误', value: 421 },
  UNPROCESSABLE_ENTITY: { label: '不可处理的实体', value: 422 },
  FAILED_DEPENDENCY: { label: '失败依赖', value: 424 },
  PRECONDITION_REQUIRED: { label: '需要先决条件', value: 428 },
  TOO_MANY_REQUESTS: { label: '请求过多', value: 429 },
  INTERNAL_SERVER_ERROR: { label: '服务器内部错误', value: 500 },
  NOT_IMPLEMENTED: { label: '服务器不支持', value: 501 },
  BAD_GATEWAY: { label: '网关错误', value: 502 },
  SERVICE_UNAVAILABLE: { label: '服务不可用', value: 503 },
  GATEWAY_TIMEOUT: { label: '网关超时', value: 504 },
  HTTP_VERSION_NOT_SUPPORTED: { label: 'HTTP版本不受支持', value: 505 },
} as const)

export type IHttpStatusEnum = IEnumType<typeof httpStatusEnum>
