import { InternalApi } from 'nitropack/types'

export const PermissionConstant: Partial<Record<keyof InternalApi, string>> = {
  '/api/system/config/create': 'system:config:create',
  '/api/system/config/findPage': 'system:config:findPage',
  '/api/system/config/remove': 'system:config:remove',
  '/api/system/config/update': 'system:config:update',
  '/api/system/dept/create': 'system:dept:create',
  '/api/system/dept/findList': 'system:dept:findList',
  '/api/system/dept/remove': 'system:dept:remove',
  '/api/system/dept/update': 'system:dept:update',
  '/api/system/dict/data/create': 'system:dict:data:create',
  '/api/system/dict/data/findList': 'system:dict:data:findList',
  '/api/system/dict/data/remove': 'system:dict:data:remove',
  '/api/system/dict/data/update': 'system:dict:data:update',
  '/api/system/dict/type/create': 'system:dict:type:create',
  '/api/system/dict/type/findPage': 'system:dict:type:findPage',
  '/api/system/dict/type/remove': 'system:dict:type:remove',
  '/api/system/dict/type/update': 'system:dict:type:update',
  '/api/system/menu/findList': 'system:menu:findList',
  '/api/system/menu/create': 'system:menu:create',
  '/api/system/menu/remove': 'system:menu:remove',
  '/api/system/menu/update': 'system:menu:update',
  '/api/system/post/create': 'system:post:create',
  '/api/system/post/findPage': 'system:post:findPage',
  '/api/system/post/remove': 'system:post:remove',
  '/api/system/post/update': 'system:post:update',
  '/api/system/role/create': 'system:role:create',
  '/api/system/role/findPage': 'system:role:findPage',
  '/api/system/role/remove': 'system:role:remove',
  '/api/system/role/update': 'system:role:update',
  '/api/system/user/create': 'system:user:create',
  '/api/system/user/findPage': 'system:user:findPage',
  '/api/system/user/remove': 'system:user:remove',
  '/api/system/user/update': 'system:user:update',
}
