# JWT 配置
jwt:
  key: '$2b$10$nxi79AIrqNBKgNVTcBnvQu=='
  expiresIn: '7d'
  header:
  validation:
    leeway: 0

# MikroORM 配置
orm:
  clientUrl: 'mysql://root:root@127.0.0.1:3306/nitro_template'
  debug: true

# Hash 配置
hash:
  salt: '$2b$10$v0UAl9V6T7OpZAlYZKvc5O=='
  cost: 10

# Cache 配置
cache:
  ttl: 10000
  refreshThreshold: 3000
  storeUrl: 'redis://localhost:6379/0'
