# jsonwebtoken 配置
jwt:
  secret: '123456'
  signOptions: 
    expiresIn: '7d'
    encoding: 'utf8'
  verifyOptions:
    complete: true

# MikroORM 配置
orm:
  host: '127.0.0.1'
  port: 3306
  user: 'root'
  password: 'root'
  dbName: 'nitro_template'
  debug: true