# jsonwebtoken 配置
jwt:
  key: '$2b$10$nxi79AIrqNBKgNVTcBnvQu=='
  expiresIn: '10s'
  header:
  validation:
    leeway: 0

# MikroORM 配置
orm:
  host: '127.0.0.1'
  port: 3306
  user: 'root'
  password: 'root'
  dbName: 'nitro_template'
  debug: true

# Hash 配置
hash:
  salt: '$2b$10$v0UAl9V6T7OpZAlYZKvc5O=='
  cost: 10