/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Fragment: typeof import('vue')['Fragment']
  const PlusDialog: typeof import('plus-pro-components')['PlusDialog']
  const PlusDialogForm: typeof import('plus-pro-components')['PlusDialogForm']
  const PlusForm: typeof import('plus-pro-components')['PlusForm']
  const PlusLayout: typeof import('plus-pro-components')['PlusLayout']
  const PlusPage: typeof import('plus-pro-components')['PlusPage']
  const RouterView: typeof import('vue-router')['RouterView']
  const authApi: typeof import('../apis/auth')['authApi']
  const captchaApi: typeof import('../apis/captcha')['captchaApi']
  const computed: typeof import('vue')['computed']
  const configApi: typeof import('../apis/config')['configApi']
  const createPinia: typeof import('pinia')['createPinia']
  const createWebHistory: typeof import('vue-router')['createWebHistory']
  const currentUserApi: typeof import('../apis/current-user')['currentUserApi']
  const defineComponent: typeof import('vue')['defineComponent']
  const defineStore: typeof import('pinia')['defineStore']
  const deptApi: typeof import('../apis/dept')['deptApi']
  const dictDataApi: typeof import('../apis/dict-data')['dictDataApi']
  const dictTypeApi: typeof import('../apis/dict-type')['dictTypeApi']
  const h: typeof import('vue')['h']
  const menuApi: typeof import('../apis/menu')['menuApi']
  const monitorOnlineApi: typeof import('../apis/monitor/online')['monitorOnlineApi']
  const onlineApi: typeof import('../apis/monitor/online')['onlineApi']
  const postApi: typeof import('../apis/post')['postApi']
  const postAuthApi: typeof import('../apis/post-auth')['postAuthApi']
  const ref: typeof import('vue')['ref']
  const roleApi: typeof import('../apis/role')['roleApi']
  const roleAuthApi: typeof import('../apis/role-auth')['roleAuthApi']
  const roleMenuApi: typeof import('../apis/role-menu')['roleMenuApi']
  const router: typeof import('../router/index')['router']
  const routes: typeof import('../router/routes')['routes']
  const shallowRef: typeof import('vue')['shallowRef']
  const store: typeof import('../store/index')['store']
  const systemConfigApi: typeof import('../apis/system/config')['systemConfigApi']
  const systemDeptApi: typeof import('../apis/system/dept')['systemDeptApi']
  const systemDictDataApi: typeof import('../apis/system/dict-data')['systemDictDataApi']
  const systemDictTypeApi: typeof import('../apis/system/dict-type')['systemDictTypeApi']
  const systemMenuApi: typeof import('../apis/system/menu')['systemMenuApi']
  const systemPostApi: typeof import('../apis/system/post')['systemPostApi']
  const systemPostAuthApi: typeof import('../apis/system/post-auth')['systemPostAuthApi']
  const systemRoleApi: typeof import('../apis/system/role')['systemRoleApi']
  const systemRoleAuthApi: typeof import('../apis/system/role-auth')['systemRoleAuthApi']
  const systemRoleMenuApi: typeof import('../apis/system/role-menu')['systemRoleMenuApi']
  const systemUserApi: typeof import('../apis/system/user')['systemUserApi']
  const unref: typeof import('vue')['unref']
  const useAppStore: typeof import('../store/useAppStore')['useAppStore']
  const useLocaleStore: typeof import('../store/useLocaleStore')['useLocaleStore']
  const usePermissionStore: typeof import('../store/usePermissionStore')['usePermissionStore']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const useUserStore: typeof import('../store/useUserStore')['useUserStore']
  const userApi: typeof import('../apis/user')['userApi']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Ref, ComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { FieldValues, PlusColumn, PlusDialogProps, PlusFormProps, PlusPageInstance, PlusPageProps, PlusHeaderProps, PlusSidebarProps } from 'plus-pro-components'
  import('plus-pro-components')
}
