/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Fragment: typeof import('vue')['Fragment']
  const PlusDialog: typeof import('plus-pro-components')['PlusDialog']
  const PlusDialogForm: typeof import('plus-pro-components')['PlusDialogForm']
  const PlusForm: typeof import('plus-pro-components')['PlusForm']
  const PlusLayout: typeof import('plus-pro-components')['PlusLayout']
  const PlusPage: typeof import('plus-pro-components')['PlusPage']
  const RouterView: typeof import('vue-router')['RouterView']
  const authApi: typeof import('../apis/auth')['authApi']
  const computed: typeof import('vue')['computed']
  const configApi: typeof import('../apis/config')['configApi']
  const createPinia: typeof import('pinia')['createPinia']
  const createWebHistory: typeof import('vue-router')['createWebHistory']
  const defineComponent: typeof import('vue')['defineComponent']
  const defineStore: typeof import('pinia')['defineStore']
  const deptApi: typeof import('../apis/dept')['deptApi']
  const dictDataApi: typeof import('../apis/dict-data')['dictDataApi']
  const dictTypeApi: typeof import('../apis/dict-type')['dictTypeApi']
  const h: typeof import('vue')['h']
  const menuApi: typeof import('../apis/menu')['menuApi']
  const postApi: typeof import('../apis/post')['postApi']
  const ref: typeof import('vue')['ref']
  const roleApi: typeof import('../apis/role')['roleApi']
  const roleAuthApi: typeof import('../apis/roleAuth')['roleAuthApi']
  const router: typeof import('../router/index')['router']
  const routes: typeof import('../router/routes')['routes']
  const store: typeof import('../store/index')['store']
  const unref: typeof import('vue')['unref']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const useUserStore: typeof import('../store/useUserStore')['useUserStore']
  const userApi: typeof import('../apis/user')['userApi']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Ref, ComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { FieldValues, PlusColumn, PlusDialogProps, PlusFormProps, PlusPageInstance, PlusPageProps, PlusHeaderProps, PlusSidebarProps } from 'plus-pro-components'
  import('plus-pro-components')
}
