/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const RouterView: typeof import('vue-router')['RouterView']
  const ajax: typeof import('../utils/ajax')['ajax']
  const authApi: typeof import('../apis/auth')['authApi']
  const computed: typeof import('vue')['computed']
  const configApi: typeof import('../apis/config')['configApi']
  const createPinia: typeof import('pinia')['createPinia']
  const createWebHistory: typeof import('vue-router')['createWebHistory']
  const defineComponent: typeof import('vue')['defineComponent']
  const defineStore: typeof import('pinia')['defineStore']
  const delay: typeof import('../../shared/utils/async')['delay']
  const h: typeof import('vue')['h']
  const listToTree: typeof import('../../shared/utils/transform')['listToTree']
  const ref: typeof import('vue')['ref']
  const router: typeof import('../router/index')['router']
  const routes: typeof import('../router/routes')['routes']
  const store: typeof import('../store/index')['store']
  const unref: typeof import('vue')['unref']
  const useRoute: typeof import('vue-router')['useRoute']
  const useRouter: typeof import('vue-router')['useRouter']
  const useUserStore: typeof import('../store/useUserStore')['useUserStore']
  const userApi: typeof import('../apis/user')['userApi']
}
