/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const RouterView: typeof import('vue-router')['RouterView']
  const ajax: typeof import('./utils/ajax')['ajax']
  const authApi: typeof import('./apis/auth')['authApi']
  const computed: typeof import('vue')['computed']
  const createPinia: typeof import('pinia')['createPinia']
  const createRouter: typeof import('vue-router')['createRouter']
  const createWebHistory: typeof import('vue-router')['createWebHistory']
  const defineComponent: typeof import('vue')['defineComponent']
  const defineStore: typeof import('pinia')['defineStore']
  const ref: typeof import('vue')['ref']
  const router: typeof import('./router/index')['router']
  const store: typeof import('./store/index')['store']
  const unref: typeof import('vue')['unref']
  const useUserStore: typeof import('./store/useUserStore')['useUserStore']
  const userApi: typeof import('./apis/user')['userApi']
}
